server:
  port: 7001


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka/

    register-with-eureka: false #不在注册中心注册自己
    fetch-registry: false #值为false 表示自己为注册中心